package margo

import (
	stdhtml "html"
	"strings"

	"github.com/a-h/templ"
)

// PDFBrand returns the small editorial furniture shared by PDF projections.
// The supplied logo is already materialized, so PDF rendering remains offline
// and does not depend on the surrounding application shell.
func PDFBrand(name, pageTitle string, logo AssetRef) Brand {
	name = strings.TrimSpace(name)
	if name == "" {
		name = "Margo"
	}
	pageTitle = strings.TrimSpace(pageTitle)
	if pageTitle == "" {
		pageTitle = "Document"
	}

	return Brand{
		Header:  templ.Raw(`<span class="margo-pdf-brand-name">` + stdhtml.EscapeString(name) + `</span>`),
		Footer:  templ.Raw(`<span class="margo-pdf-page-title">` + stdhtml.EscapeString(pageTitle) + `</span><span class="margo-pdf-generated">Generated by Margo</span>`),
		Logo:    logo,
		LogoAlt: name,
	}
}

// WithPDFBrand applies PDFBrand after other standalone options. This keeps
// command-line title overrides visible in the generated footer.
func WithPDFBrand(name string, logo AssetRef) StandaloneOption {
	return func(config *standaloneConfig) error {
		brand := PDFBrand(name, config.title, logo)
		if err := brand.Validate(); err != nil {
			return err
		}
		config.brand = brand
		return nil
	}
}
