package margo

import (
	"context"
	"fmt"
	"net/http"
	"net/http/httptest"
	"os"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/a-h/templ"
	"github.com/chromedp/cdproto/css"
	"github.com/chromedp/cdproto/dom"
	"github.com/chromedp/cdproto/emulation"
	cdpruntime "github.com/chromedp/cdproto/runtime"
	"github.com/chromedp/chromedp"
)

func TestStandaloneNarrowEntryPrioritizesReadingBeforeExhaustiveNavigation(t *testing.T) {
	browserPath := installedPrintTestChromium()
	if browserPath == "" {
		t.Skip("installed Chromium-family browser unavailable")
	}
	var source strings.Builder
	source.WriteString("# Visual foundation\n\nPurpose before navigation.\n")
	for index := 1; index <= 12; index++ {
		source.WriteString("\n## Section ")
		source.WriteString(string(rune('A' + index - 1)))
		source.WriteString("\n\nEvidence.\n\n### Detail\n\nDeep evidence.\n")
	}
	result := mustRenderSource(t, source.String())
	component, err := RenderStandalone(
		result,
		WithTableOfContents(),
		WithBrand(Brand{
			Header:    templ.Raw(`<span>Margo visual foundation</span>`),
			Footer:    templ.Raw(`<span>Generated by Margo</span>`),
			Watermark: "REVIEW COPY",
			Stamps:    []string{"v1.0.0", "review required"},
		}),
	)
	if err != nil {
		t.Fatal(err)
	}
	markup := renderComponent(t, component)
	server := httptest.NewServer(http.HandlerFunc(func(writer http.ResponseWriter, _ *http.Request) {
		writer.Header().Set("Content-Type", "text/html; charset=utf-8")
		_, _ = writer.Write([]byte(markup))
	}))
	defer server.Close()

	allocatorOptions := append([]chromedp.ExecAllocatorOption{}, chromedp.DefaultExecAllocatorOptions[:]...)
	allocatorOptions = append(allocatorOptions, chromedp.ExecPath(browserPath))
	allocatorContext, cancelAllocator := chromedp.NewExecAllocator(context.Background(), allocatorOptions...)
	defer cancelAllocator()
	browserContext, cancelBrowser := chromedp.NewContext(allocatorContext)
	defer cancelBrowser()
	ctx, cancel := context.WithTimeout(browserContext, 20*time.Second)
	defer cancel()

	var state struct {
		ArticleTop       float64 `json:"articleTop"`
		TitleBottom      float64 `json:"titleBottom"`
		TOCTop           float64 `json:"tocTop"`
		TOCHeight        float64 `json:"tocHeight"`
		TOCDisclosure    bool    `json:"tocDisclosure"`
		TOCOpen          bool    `json:"tocOpen"`
		TOCSectionOpen   bool    `json:"tocSectionOpen"`
		VisibleTopLinks  int     `json:"visibleTopLinks"`
		VisibleDeepLinks int     `json:"visibleDeepLinks"`
		TOCLinkHeight    float64 `json:"tocLinkHeight"`
		PageScrollWidth  float64 `json:"pageScrollWidth"`
		PageClientWidth  float64 `json:"pageClientWidth"`
		WatermarkDisplay string  `json:"watermarkDisplay"`
		ShellBorderWidth string  `json:"shellBorderWidth"`
		HeaderDirection  string  `json:"headerDirection"`
	}
	if err := chromedp.Run(ctx,
		emulation.SetDeviceMetricsOverride(390, 844, 1, false),
		chromedp.Navigate(server.URL),
		chromedp.WaitVisible(`article.margo-document h1`, chromedp.ByQuery),
		chromedp.Evaluate(`(() => {
			const article = document.querySelector('article.margo-document');
			const title = article.querySelector('h1');
			const toc = article.querySelector('.goshtoso-document__toc');
			const disclosure = toc?.querySelector('details') || null;
			const sectionDisclosure = toc?.querySelector('.goshtoso-document__toc-section-disclosure') || null;
			const link = toc?.querySelector('a') || null;
			const watermark = document.querySelector('.goshtoso-document__watermark');
			const shell = document.querySelector('.goshtoso-document');
			const header = document.querySelector('.goshtoso-document__header');
			const linkHeight = link?.getBoundingClientRect().height || 0;
			const visible = node => node.getClientRects().length > 0;
			return {
				articleTop: article.getBoundingClientRect().top,
				titleBottom: title.getBoundingClientRect().bottom,
				tocTop: toc.getBoundingClientRect().top,
				tocHeight: toc.getBoundingClientRect().height,
				tocDisclosure: Boolean(disclosure),
				tocOpen: Boolean(disclosure?.open),
				tocSectionOpen: Boolean(sectionDisclosure?.open),
				visibleTopLinks: [...toc.querySelectorAll('li[data-level="2"] > a')].filter(visible).length,
				visibleDeepLinks: [...toc.querySelectorAll('li[data-level="3"] > a, li[data-level="4"] > a')].filter(visible).length,
				tocLinkHeight: linkHeight,
				pageScrollWidth: document.documentElement.scrollWidth,
				pageClientWidth: document.documentElement.clientWidth,
				watermarkDisplay: getComputedStyle(watermark).display,
				shellBorderWidth: getComputedStyle(shell).borderTopWidth,
				headerDirection: getComputedStyle(header).flexDirection,
			};
		})()`, &state),
	); err != nil {
		t.Fatal(err)
	}
	if state.ArticleTop >= 844 || state.TitleBottom >= 844 {
		t.Fatalf("title is outside first viewport: %+v", state)
	}
	if !state.TOCDisclosure || !state.TOCOpen || state.TOCSectionOpen || state.VisibleTopLinks != 12 || state.VisibleDeepLinks != 0 {
		t.Fatalf("narrow contents are not progressively disclosed: %+v", state)
	}
	if state.TOCLinkHeight < 44 {
		t.Fatalf("contents link target height = %.1f; want at least 44", state.TOCLinkHeight)
	}
	if state.TitleBottom > state.TOCTop {
		t.Fatalf("contents precede title visually: %+v", state)
	}
	if state.PageScrollWidth != state.PageClientWidth {
		t.Fatalf("page owns horizontal overflow: %+v", state)
	}
	if state.WatermarkDisplay != "none" || state.ShellBorderWidth != "0px" || state.HeaderDirection != "column" {
		t.Fatalf("narrow standalone furniture competes with reading: %+v", state)
	}
}

func TestStandaloneWayfindingHasTouchFocusAndCurrentLocationFeedback(t *testing.T) {
	browserPath := installedPrintTestChromium()
	if browserPath == "" {
		t.Skip("installed Chromium-family browser unavailable")
	}
	result := mustRenderSource(t, "# Visual foundation\n\nPurpose.\n\n## Evidence\n\nBody.\n\n## Decision\n\nBody.\n")
	component, err := RenderStandalone(result, WithTableOfContents())
	if err != nil {
		t.Fatal(err)
	}
	markup := renderComponent(t, component)
	server := httptest.NewServer(http.HandlerFunc(func(writer http.ResponseWriter, _ *http.Request) {
		writer.Header().Set("Content-Type", "text/html; charset=utf-8")
		_, _ = writer.Write([]byte(markup))
	}))
	defer server.Close()

	allocatorOptions := append([]chromedp.ExecAllocatorOption{}, chromedp.DefaultExecAllocatorOptions[:]...)
	allocatorOptions = append(allocatorOptions, chromedp.ExecPath(browserPath))
	allocatorContext, cancelAllocator := chromedp.NewExecAllocator(context.Background(), allocatorOptions...)
	defer cancelAllocator()
	browserContext, cancelBrowser := chromedp.NewContext(allocatorContext)
	defer cancelBrowser()
	ctx, cancel := context.WithTimeout(browserContext, 20*time.Second)
	defer cancel()

	var state struct {
		SummaryHeight float64 `json:"summaryHeight"`
		BackHeight    float64 `json:"backHeight"`
		OutlineWidth  string  `json:"outlineWidth"`
		OutlineStyle  string  `json:"outlineStyle"`
		Current       string  `json:"current"`
	}
	if err := chromedp.Run(ctx,
		emulation.SetDeviceMetricsOverride(390, 844, 1, false),
		chromedp.Navigate(server.URL),
		chromedp.WaitVisible(`article.margo-document h1`, chromedp.ByQuery),
		chromedp.ActionFunc(func(ctx context.Context) error {
			if err := css.Enable().Do(ctx); err != nil {
				return err
			}
			document, err := dom.GetDocument().Do(ctx)
			if err != nil {
				return err
			}
			nodeID, err := dom.QuerySelector(document.NodeID, `.goshtoso-document__toc summary`).Do(ctx)
			if err != nil {
				return err
			}
			return css.ForcePseudoState(nodeID, []string{"focus-visible"}).Do(ctx)
		}),
		chromedp.Evaluate(`(() => {
			const summary = document.querySelector('.goshtoso-document__toc summary');
			const details = summary.closest('details');
			const firstLink = details.querySelector('a');
			const back = document.querySelector('.goshtoso-document__back-to-contents');
			const focused = getComputedStyle(summary);
			details.open = true;
			location.hash = firstLink.hash;
			window.dispatchEvent(new HashChangeEvent('hashchange'));
			return {
				summaryHeight: summary.getBoundingClientRect().height,
				backHeight: back.getBoundingClientRect().height,
				outlineWidth: focused.outlineWidth,
				outlineStyle: focused.outlineStyle,
				current: firstLink.getAttribute('aria-current') || '',
			};
		})()`, &state),
	); err != nil {
		t.Fatal(err)
	}
	if state.SummaryHeight < 44 || state.BackHeight < 44 {
		t.Fatalf("wayfinding targets are undersized: %+v", state)
	}
	if state.OutlineWidth != "2px" || state.OutlineStyle == "none" {
		t.Fatalf("contents focus is not visibly styled: %+v", state)
	}
	if state.Current != "location" {
		t.Fatalf("current contents location = %q, want location", state.Current)
	}
}

func TestStandaloneVisualAcceptanceMatrix(t *testing.T) {
	browserPath := installedPrintTestChromium()
	if browserPath == "" {
		t.Skip("installed Chromium-family browser unavailable")
	}
	const source = `# A deliberately long visual foundation title

Purpose and scope for readers entering this technical document.

## Evidence

Ordinary prose establishes the sustained reading measure for the document surface.

### Runtime

#### Constraints

##### Operational note

###### Trace label

| Name | Value |
| --- | ---: |
| alpha | 1 |
| beta | 2 |

~~~go
fmt.Println("local overflow remains inside code")
~~~
`
	result := mustRenderSource(t, source)
	allocatorOptions := append([]chromedp.ExecAllocatorOption{}, chromedp.DefaultExecAllocatorOptions[:]...)
	allocatorOptions = append(allocatorOptions, chromedp.ExecPath(browserPath))
	allocatorContext, cancelAllocator := chromedp.NewExecAllocator(context.Background(), allocatorOptions...)
	defer cancelAllocator()

	for _, theme := range []ThemeName{ThemeModern, ThemeMinimal} {
		for _, mode := range []ColorMode{ColorModeLight, ColorModeDark} {
			component, err := RenderStandalone(
				result,
				WithStandaloneTheme(theme),
				WithStandaloneColorMode(mode),
				WithTableOfContents(),
				WithBrand(Brand{Watermark: "REVIEW COPY"}),
			)
			if err != nil {
				t.Fatal(err)
			}
			markup := renderComponent(t, component)
			server := httptest.NewServer(http.HandlerFunc(func(writer http.ResponseWriter, _ *http.Request) {
				writer.Header().Set("Content-Type", "text/html; charset=utf-8")
				_, _ = writer.Write([]byte(markup))
			}))

			for _, width := range []int64{390, 1440} {
				name := string(theme) + "/" + string(mode) + "/" + fmt.Sprint(width)
				t.Run(name, func(t *testing.T) {
					browserContext, cancelBrowser := chromedp.NewContext(allocatorContext)
					defer cancelBrowser()
					ctx, cancel := context.WithTimeout(browserContext, 20*time.Second)
					defer cancel()
					var state struct {
						Theme             string  `json:"theme"`
						Mode              string  `json:"mode"`
						PageScrollWidth   float64 `json:"pageScrollWidth"`
						PageClientWidth   float64 `json:"pageClientWidth"`
						TitleBottom       float64 `json:"titleBottom"`
						LeadBottom        float64 `json:"leadBottom"`
						TOCOpen           bool    `json:"tocOpen"`
						TOCSectionOpen    bool    `json:"tocSectionOpen"`
						ShellBorder       string  `json:"shellBorder"`
						WatermarkDisplay  string  `json:"watermarkDisplay"`
						H1Size            float64 `json:"h1Size"`
						LeadSize          float64 `json:"leadSize"`
						BodySize          float64 `json:"bodySize"`
						H5Size            float64 `json:"h5Size"`
						H6Size            float64 `json:"h6Size"`
						H6Transform       string  `json:"h6Transform"`
						ProseMeasure      float64 `json:"proseMeasure"`
						Contrast          float64 `json:"contrast"`
						LeadContrast      float64 `json:"leadContrast"`
						BodyColor         string  `json:"bodyColor"`
						ArticleBackground string  `json:"articleBackground"`
						DuplicateIDCount  int     `json:"duplicateIDCount"`
						CodeOverflow      string  `json:"codeOverflow"`
					}
					if err := chromedp.Run(ctx,
						emulation.SetDeviceMetricsOverride(width, 900, 1, false),
						chromedp.Navigate(server.URL),
						chromedp.WaitVisible(`article.margo-document h1`, chromedp.ByQuery),
						chromedp.Evaluate(`(() => {
							const article = document.querySelector('.margo-document');
							const title = article.querySelector('h1');
							const lead = article.querySelector('.margo-document__lead');
							const body = [...article.querySelectorAll('p')].find(node => !node.classList.contains('margo-document__lead'));
							const parse = value => {
								const canvas = document.createElement('canvas');
								canvas.width = canvas.height = 1;
								const context = canvas.getContext('2d');
								context.fillStyle = value;
								context.fillRect(0, 0, 1, 1);
								return [...context.getImageData(0, 0, 1, 1).data].slice(0, 3);
							};
							const luminance = value => {
								const rgb = parse(value).map(channel => channel / 255).map(channel => channel <= .03928 ? channel / 12.92 : ((channel + .055) / 1.055) ** 2.4);
								return .2126 * rgb[0] + .7152 * rgb[1] + .0722 * rgb[2];
							};
							const foreground = luminance(getComputedStyle(body).color);
							const background = luminance(getComputedStyle(article).backgroundColor);
							const leadForeground = luminance(getComputedStyle(lead).color);
							const ids = [...document.querySelectorAll('[id]')].map(node => node.id);
							const bodyStyle = getComputedStyle(body);
							const probe = document.createElement('canvas').getContext('2d');
							probe.font = bodyStyle.font;
							return {
								theme: document.documentElement.dataset.theme,
								mode: document.documentElement.dataset.colorMode,
								pageScrollWidth: document.documentElement.scrollWidth,
								pageClientWidth: document.documentElement.clientWidth,
								titleBottom: title.getBoundingClientRect().bottom,
								leadBottom: lead.getBoundingClientRect().bottom,
								tocOpen: document.querySelector('.goshtoso-document__toc-disclosure').open,
								tocSectionOpen: document.querySelector('.goshtoso-document__toc-section-disclosure').open,
								shellBorder: getComputedStyle(document.querySelector('.goshtoso-document')).borderTopWidth,
								watermarkDisplay: getComputedStyle(document.querySelector('.goshtoso-document__watermark')).display,
								h1Size: parseFloat(getComputedStyle(title).fontSize),
								leadSize: parseFloat(getComputedStyle(lead).fontSize),
								bodySize: parseFloat(bodyStyle.fontSize),
								h5Size: parseFloat(getComputedStyle(article.querySelector('h5')).fontSize),
								h6Size: parseFloat(getComputedStyle(article.querySelector('h6')).fontSize),
								h6Transform: getComputedStyle(article.querySelector('h6')).textTransform,
								proseMeasure: parseFloat(bodyStyle.maxWidth) / probe.measureText('0').width,
								contrast: (Math.max(foreground, background) + .05) / (Math.min(foreground, background) + .05),
								leadContrast: (Math.max(leadForeground, background) + .05) / (Math.min(leadForeground, background) + .05),
								bodyColor: bodyStyle.color,
								articleBackground: getComputedStyle(article).backgroundColor,
								duplicateIDCount: ids.length - new Set(ids).size,
								codeOverflow: getComputedStyle(article.querySelector('pre')).overflowX,
							};
						})()`, &state),
					); err != nil {
						t.Fatal(err)
					}
					if state.Theme != string(theme) || state.Mode != string(mode) {
						t.Fatalf("theme identity mismatch: %+v", state)
					}
					if state.PageScrollWidth != state.PageClientWidth || state.DuplicateIDCount != 0 {
						t.Fatalf("document containment or identity failed: %+v", state)
					}
					if state.WatermarkDisplay != "none" || state.Contrast < 4.5 || state.LeadContrast < 4.5 {
						t.Fatalf("screen visibility or contrast failed: %+v", state)
					}
					if !(state.H1Size > state.LeadSize && state.LeadSize > state.BodySize && state.H5Size > state.H6Size && state.H6Transform == "uppercase") {
						t.Fatalf("typographic hierarchy failed: %+v", state)
					}
					if state.ProseMeasure < 65 || state.ProseMeasure > 76 || state.CodeOverflow != "auto" {
						t.Fatalf("reading measure or local code overflow failed: %+v", state)
					}
					if width == 390 {
						if state.TitleBottom >= 900 || state.LeadBottom >= 900 || !state.TOCOpen || state.TOCSectionOpen || state.ShellBorder != "0px" {
							t.Fatalf("narrow entry failed: %+v", state)
						}
					} else if !state.TOCOpen || !state.TOCSectionOpen || state.ShellBorder == "0px" {
						t.Fatalf("wide document furniture failed: %+v", state)
					}
				})
			}
			server.Close()
		}
	}
}

func TestFullFeatureStandaloneHasNoNarrowClippingOrConsoleWarnings(t *testing.T) {
	browserPath := installedPrintTestChromium()
	if browserPath == "" {
		t.Skip("installed Chromium-family browser unavailable")
	}
	source, err := os.ReadFile("testdata/markdown/margo-full-feature-set.md")
	if err != nil {
		t.Fatal(err)
	}
	compiler := New(WithHostPolicy(Policy{RawHTML: RawHTMLSanitized, OutputBytes: MaxOutputBytes}))
	document, err := compiler.Compile(context.Background(), Source{Name: "margo-full-feature-set.md", Content: source})
	if err != nil {
		t.Fatal(err)
	}
	result, err := compiler.Render(context.Background(), document, WithTableSort(TableSortClient))
	if err != nil {
		t.Fatal(err)
	}
	logo, err := EmbeddedAsset("logo.svg")
	if err != nil {
		t.Fatal(err)
	}
	component, err := RenderStandalone(
		result,
		WithTableOfContents(),
		WithBrand(Brand{
			Header:    templ.Raw(`<span><strong>Margo</strong> · full feature benchmark</span><span>Markdown for Goshtoso</span>`),
			Footer:    templ.Raw(`<span>Source: margo-full-feature-set.md</span><span>theme modern · human artifact</span>`),
			Logo:      logo,
			LogoAlt:   "Margo mark",
			Backdrop:  logo,
			Watermark: "Optimistic benchmark",
			Stamps:    []string{"v0.0.1", "optimistic", "review required"},
		}),
	)
	if err != nil {
		t.Fatal(err)
	}
	markup := renderComponent(t, component)
	server := httptest.NewServer(http.HandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
		switch request.URL.Path {
		case "/":
			writer.Header().Set("Content-Type", "text/html; charset=utf-8")
			_, _ = writer.Write([]byte(markup))
		case "/assets/logo.svg":
			http.ServeFile(writer, request, "assets/logo.svg")
		case "/assets/social/margo-v0.0.1.png":
			http.ServeFile(writer, request, "assets/social/margo-v0.0.1.png")
		default:
			http.NotFound(writer, request)
		}
	}))
	defer server.Close()

	allocatorOptions := append([]chromedp.ExecAllocatorOption{}, chromedp.DefaultExecAllocatorOptions[:]...)
	allocatorOptions = append(allocatorOptions, chromedp.ExecPath(browserPath))
	allocatorContext, cancelAllocator := chromedp.NewExecAllocator(context.Background(), allocatorOptions...)
	defer cancelAllocator()
	browserContext, cancelBrowser := chromedp.NewContext(allocatorContext)
	defer cancelBrowser()
	ctx, cancel := context.WithTimeout(browserContext, 30*time.Second)
	defer cancel()

	var evidenceMu sync.Mutex
	var consoleFindings []string
	chromedp.ListenTarget(ctx, func(event any) {
		evidenceMu.Lock()
		defer evidenceMu.Unlock()
		switch typed := event.(type) {
		case *cdpruntime.EventExceptionThrown:
			consoleFindings = append(consoleFindings, typed.ExceptionDetails.Text)
		case *cdpruntime.EventConsoleAPICalled:
			if typed.Type == cdpruntime.APITypeWarning || typed.Type == cdpruntime.APITypeError || typed.Type == cdpruntime.APITypeAssert {
				consoleFindings = append(consoleFindings, string(typed.Type))
			}
		}
	})
	var state struct {
		PageScrollWidth float64  `json:"pageScrollWidth"`
		PageClientWidth float64  `json:"pageClientWidth"`
		LeadScrollWidth float64  `json:"leadScrollWidth"`
		LeadClientWidth float64  `json:"leadClientWidth"`
		ClippedText     []string `json:"clippedText"`
		BrokenImages    int      `json:"brokenImages"`
		RuntimeStatus   string   `json:"runtimeStatus"`
	}
	if err := chromedp.Run(ctx,
		cdpruntime.Enable(),
		emulation.SetDeviceMetricsOverride(390, 900, 1, false),
		chromedp.Navigate(server.URL),
		chromedp.WaitVisible(`article.margo-document h1`, chromedp.ByQuery),
		chromedp.Evaluate(`(async () => {
			if (window.margoRuntimeReady) await window.margoRuntimeReady;
			await Promise.all([...document.images].map(image => image.complete ? Promise.resolve() : new Promise(resolve => image.addEventListener('load', resolve, {once: true}))));
			const lead = document.querySelector('.margo-document__lead');
			const viewportWidth = document.documentElement.clientWidth;
			const clippedText = [...document.querySelectorAll('h1,h2,h3,h4,h5,h6,p,figcaption,caption')]
				.filter(node => {
					if (node.closest('.sr-only') || getComputedStyle(node).display === 'none') return false;
					const rect = node.getBoundingClientRect();
					if (rect.left >= -0.5 && rect.right <= viewportWidth + 0.5 && node.scrollWidth <= node.clientWidth + 1) return false;
					for (let ancestor = node.parentElement; ancestor; ancestor = ancestor.parentElement) {
						const overflow = getComputedStyle(ancestor).overflowX;
						if ((overflow === 'auto' || overflow === 'scroll') && ancestor.scrollWidth > ancestor.clientWidth) return false;
					}
					return true;
				})
				.map(node => node.textContent.trim().slice(0, 80));
			return {
				pageScrollWidth: document.documentElement.scrollWidth,
				pageClientWidth: viewportWidth,
				leadScrollWidth: lead.scrollWidth,
				leadClientWidth: lead.clientWidth,
				clippedText,
				brokenImages: [...document.images].filter(image => !image.complete || image.naturalWidth === 0).length,
				runtimeStatus: document.documentElement.dataset.margoRuntimeStatus || '',
			};
		})()`, &state, func(parameters *cdpruntime.EvaluateParams) *cdpruntime.EvaluateParams {
			return parameters.WithAwaitPromise(true)
		}),
	); err != nil {
		t.Fatal(err)
	}
	evidenceMu.Lock()
	findings := append([]string(nil), consoleFindings...)
	evidenceMu.Unlock()
	if state.PageScrollWidth != state.PageClientWidth || state.LeadScrollWidth > state.LeadClientWidth+1 || len(state.ClippedText) > 0 {
		t.Fatalf("full benchmark clips narrow content: %+v", state)
	}
	if state.BrokenImages != 0 || state.RuntimeStatus != "ready" {
		t.Fatalf("full benchmark assets/runtime are incomplete: %+v", state)
	}
	if len(findings) > 0 {
		t.Fatalf("full benchmark console warnings/errors: %v", findings)
	}
}
