// Code generated by goshtoso iconpack. DO NOT EDIT.
// Release: iconpack-c92fd330bad5
// Catalog SHA-256: c92fd330bad5cb0f28b43778e7a07207d5d5556047c846883e56d3899534c2b7

package appicons

import "github.com/araihu/goshtoso/components/icon"

type Name string

type Glyph struct {
	Name          Name
	CanonicalName string
	Namespace     string
	Product       string
	Symbol        icon.Symbol
	ColorBehavior string
}

type Config struct {
	Symbol     icon.Symbol
	Size       icon.Size
	Label      string
	Decorative bool
	RootClass  string
}

const SpriteURL = "/margo-assets/icons/page-actions.svg"

const (
	NameHeroiconsArrowDownTray16SolidArrowDownTray         Name        = "heroicons-arrow-down-tray-16-solid-arrow-down-tray"
	IconHeroiconsArrowDownTray16SolidArrowDownTray         icon.Symbol = "heroicons-arrow-down-tray-16-solid-arrow-down-tray"
	NameHeroiconsArrowTopRight16SolidArrowTopRightOnSquare Name        = "heroicons-arrow-top-right-16-solid-arrow-top-right-on-square"
	IconHeroiconsArrowTopRight16SolidArrowTopRightOnSquare icon.Symbol = "heroicons-arrow-top-right-16-solid-arrow-top-right-on-square"
	NameHeroiconsCopy16SolidClipboard                      Name        = "heroicons-copy-16-solid-clipboard"
	IconHeroiconsCopy16SolidClipboard                      icon.Symbol = "heroicons-copy-16-solid-clipboard"
	NameHeroiconsDocumentText16SolidDocumentText           Name        = "heroicons-document-text-16-solid-document-text"
	IconHeroiconsDocumentText16SolidDocumentText           icon.Symbol = "heroicons-document-text-16-solid-document-text"
	NameHeroiconsPrinter16SolidPrinter                     Name        = "heroicons-printer-16-solid-printer"
	IconHeroiconsPrinter16SolidPrinter                     icon.Symbol = "heroicons-printer-16-solid-printer"
)

var Glyphs = []Glyph{
	{Name: NameHeroiconsArrowDownTray16SolidArrowDownTray, CanonicalName: "heroicons-arrow-down-tray-16-solid-arrow-down-tray", Namespace: "custom", Product: "heroicons-arrow-down-tray", Symbol: IconHeroiconsArrowDownTray16SolidArrowDownTray, ColorBehavior: "currentColor"},
	{Name: NameHeroiconsArrowTopRight16SolidArrowTopRightOnSquare, CanonicalName: "heroicons-arrow-top-right-16-solid-arrow-top-right-on-square", Namespace: "custom", Product: "heroicons-arrow-top-right", Symbol: IconHeroiconsArrowTopRight16SolidArrowTopRightOnSquare, ColorBehavior: "currentColor"},
	{Name: NameHeroiconsCopy16SolidClipboard, CanonicalName: "heroicons-copy-16-solid-clipboard", Namespace: "custom", Product: "heroicons-copy", Symbol: IconHeroiconsCopy16SolidClipboard, ColorBehavior: "currentColor"},
	{Name: NameHeroiconsDocumentText16SolidDocumentText, CanonicalName: "heroicons-document-text-16-solid-document-text", Namespace: "custom", Product: "heroicons-document-text", Symbol: IconHeroiconsDocumentText16SolidDocumentText, ColorBehavior: "currentColor"},
	{Name: NameHeroiconsPrinter16SolidPrinter, CanonicalName: "heroicons-printer-16-solid-printer", Namespace: "custom", Product: "heroicons-printer", Symbol: IconHeroiconsPrinter16SolidPrinter, ColorBehavior: "currentColor"},
}

func Lookup(name Name) (Glyph, bool) {
	for _, glyph := range Glyphs {
		if glyph.Name == name {
			return glyph, true
		}
	}
	return Glyph{}, false
}

func Icon(cfg Config) icon.Instance {
	return icon.Icon(icon.Config{SpriteURL: SpriteURL, Symbol: cfg.Symbol, Size: cfg.Size, Label: cfg.Label, Decorative: cfg.Decorative, RootClass: cfg.RootClass})
}
