package main

import (
	"bytes"
	"context"
	"errors"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"

	margo "github.com/araihu/margo"
	"github.com/araihu/margo/pdf"
	"github.com/araihu/margo/pdf/engines"
)

func TestPDFRequiresExplicitOutput(t *testing.T) {
	command := NewRootCommand(Dependencies{
		Stdin: strings.NewReader("# Page\n"), Stdout: io.Discard, Stderr: io.Discard,
		Build: testBuildInfo(), WorkingDirectory: t.TempDir(),
	})
	command.SetArgs([]string{"pdf", "-"})
	if err := command.ExecuteContext(context.Background()); cliDiagnosticCode(err) != "cli.output_required" {
		t.Fatalf("error = %v", err)
	}
}

func TestPDFHelpExplainsPreflightEngineDiscoveryAndRecovery(t *testing.T) {
	var stdout bytes.Buffer
	command := NewRootCommand(Dependencies{Stdout: &stdout, Build: testBuildInfo()})
	command.SetArgs([]string{"pdf", "--help"})
	if err := command.ExecuteContext(context.Background()); err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{"margo check", "margo doctor", "--output", "--base-url", "--title", "--lang", "--image-overflow"} {
		if !strings.Contains(stdout.String(), want) {
			t.Fatalf("PDF help missing %q:\n%s", want, stdout.String())
		}
	}
}

func TestPDFCommandPropagatesTitleAndLanguageOverrides(t *testing.T) {
	engine := &capturingEngine{name: "native"}
	probe := engines.Probe{Native: func(context.Context) (pdf.Engine, engines.Candidate) {
		return engine, engines.Candidate{Name: "native", Version: "test", Compiled: true, Available: true}
	}}
	output := filepath.Join(t.TempDir(), "metadata.pdf")
	command := NewRootCommand(Dependencies{
		Stdin: strings.NewReader("# Original\n"), EngineProbe: probe, Stderr: io.Discard,
		Build: testBuildInfo(), WorkingDirectory: t.TempDir(),
		NextExecutionID: func() margo.ExecutionID { return "cli-pdf-metadata" },
	})
	command.SetArgs([]string{"pdf", "-", "--output", output, "--engine", "native", "--title", "Published PDF", "--lang", "pt-BR"})
	if err := command.ExecuteContext(context.Background()); err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		`<title>Published PDF</title>`,
		`<html lang="pt-BR"`,
		`class="goshtoso-document__header"`,
		`class="margo-pdf-brand-name">Margo</span>`,
		`class="goshtoso-document__footer"`,
		`class="margo-pdf-page-title">Published PDF</span>`,
		`class="margo-pdf-generated">Generated by Margo</span>`,
	} {
		if !bytes.Contains(engine.request.HTML, []byte(want)) {
			t.Fatalf("PDF renderer input missing %q", want)
		}
	}
}

func TestPDFCommandUsesReadableDefaultMarginsAndAllowsExplicitZero(t *testing.T) {
	tests := []struct {
		name      string
		markdown  string
		extraArgs []string
		wantPage  pdf.PageConfig
	}{
		{
			name:     "readable document defaults",
			markdown: "# Page\n",
			wantPage: pdf.PageConfig{
				Size: pdf.PageA4, Orientation: pdf.Portrait,
				Margins: pdf.Margins{Top: 24, Right: 22, Bottom: 26, Left: 22},
			},
		},
		{
			name:     "document selects Letter landscape and partial margins",
			markdown: "---\nmargo:\n  page:\n    size: Letter\n    orientation: landscape\n    imageOverflow: allow\n    margins:\n      top: 8\n      right: 9\n      bottom: 0\n---\n# Page\n",
			wantPage: pdf.PageConfig{
				Size: pdf.PageLetter, Orientation: pdf.Landscape, ImageOverflow: pdf.ImageOverflowAllow,
				Margins: pdf.Margins{Top: 8, Right: 9, Bottom: 0, Left: 22},
			},
		},
		{
			name:     "explicit CLI geometry overrides document",
			markdown: "---\nmargo:\n  page:\n    size: Letter\n    orientation: landscape\n    margins:\n      top: 8\n      right: 9\n      bottom: 10\n      left: 11\n---\n# Page\n",
			extraArgs: []string{
				"--page-size", "A4", "--orientation", "portrait",
				"--image-overflow", "limit",
				"--margin-top", "0", "--margin-right", "0",
				"--margin-bottom", "0", "--margin-left", "0",
			},
			wantPage: pdf.PageConfig{Size: pdf.PageA4, Orientation: pdf.Portrait, ImageOverflow: pdf.ImageOverflowLimit},
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			engine := &capturingEngine{name: "native"}
			probe := engines.Probe{Native: func(context.Context) (pdf.Engine, engines.Candidate) {
				return engine, engines.Candidate{Name: "native", Version: "test", Compiled: true, Available: true}
			}}
			output := filepath.Join(t.TempDir(), "page.pdf")
			command := NewRootCommand(Dependencies{
				Stdin: strings.NewReader(test.markdown), EngineProbe: probe, Stderr: io.Discard,
				Build: testBuildInfo(), WorkingDirectory: t.TempDir(),
				NextExecutionID: func() margo.ExecutionID { return "cli-pdf-margins" },
			})
			args := []string{"pdf", "-", "--output", output, "--engine", "native"}
			command.SetArgs(append(args, test.extraArgs...))
			if err := command.ExecuteContext(context.Background()); err != nil {
				t.Fatal(err)
			}
			if engine.request.Page != test.wantPage {
				t.Fatalf("page = %+v, want %+v", engine.request.Page, test.wantPage)
			}
		})
	}
}

func TestPDFCommandUsesStaticEmbedProjectionFromTrustedPolicy(t *testing.T) {
	engine := &capturingEngine{name: "native"}
	probe := engines.Probe{Native: func(context.Context) (pdf.Engine, engines.Candidate) {
		return engine, engines.Candidate{Name: "native", Version: "test", Compiled: true, Available: true}
	}}
	root := t.TempDir()
	policyPath := filepath.Join(root, "policy.json")
	policy := `{"schemaVersion":"margo-policy/v1","iframe":{"allowedOrigins":["https://video.example.com"],"projections":{"html":"interactive","pdf":"static-link","site":"deny","deck":"deny"}}}`
	if err := os.WriteFile(policyPath, []byte(policy), 0o600); err != nil {
		t.Fatal(err)
	}
	output := filepath.Join(root, "embed.pdf")
	markdown := "<iframe src=\"https://video.example.com/watch/123\" title=\"Architecture overview\"></iframe>\n"
	command := NewRootCommand(Dependencies{
		Stdin: strings.NewReader(markdown), EngineProbe: probe, Stderr: io.Discard,
		Build: testBuildInfo(), WorkingDirectory: root,
		NextExecutionID: func() margo.ExecutionID { return "cli-pdf-policy" },
	})
	command.SetArgs([]string{"pdf", "-", "--output", output, "--engine", "native", "--policy", policyPath})
	if err := command.ExecuteContext(context.Background()); err != nil {
		t.Fatal(err)
	}
	if bytes.Contains(engine.request.HTML, []byte("<iframe")) {
		t.Fatalf("PDF renderer received interactive iframe")
	}
	for _, want := range []string{`class="margo-embed__link"`, `href="https://video.example.com/watch/123"`} {
		if !bytes.Contains(engine.request.HTML, []byte(want)) {
			t.Fatalf("PDF renderer input missing %q", want)
		}
	}
}

func TestPDFLinkFlagsUseSafeDefaultsAndExplicitResolution(t *testing.T) {
	tests := []struct {
		name           string
		flags          pdfLinkFlags
		policyExplicit bool
		wantPolicy     pdf.RelativeLinkPolicy
		wantBase       string
		wantCode       string
	}{
		{name: "default strips", flags: pdfLinkFlags{Policy: "strip"}, wantPolicy: pdf.RelativeLinksStrip},
		{
			name:       "base URL implies resolution",
			flags:      pdfLinkFlags{Policy: "strip", BaseURL: "https://docs.example.com/manual/"},
			wantPolicy: pdf.RelativeLinksResolve, wantBase: "https://docs.example.com/manual/",
		},
		{
			name:  "explicit resolution",
			flags: pdfLinkFlags{Policy: "resolve", BaseURL: "https://docs.example.com/manual/"}, policyExplicit: true,
			wantPolicy: pdf.RelativeLinksResolve, wantBase: "https://docs.example.com/manual/",
		},
		{
			name:  "resolution requires base",
			flags: pdfLinkFlags{Policy: "resolve"}, policyExplicit: true,
			wantCode: "cli.relative_link_base_required",
		},
		{
			name:  "explicit non-resolution rejects unused base",
			flags: pdfLinkFlags{Policy: "strip", BaseURL: "https://docs.example.com/manual/"}, policyExplicit: true,
			wantCode: "cli.relative_link_options_invalid",
		},
		{
			name:  "unknown policy",
			flags: pdfLinkFlags{Policy: "surprise"}, policyExplicit: true,
			wantCode: "cli.relative_link_policy_invalid",
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			got, err := test.flags.config(test.policyExplicit)
			if test.wantCode != "" {
				if cliDiagnosticCode(err) != test.wantCode {
					t.Fatalf("error = %v, want %s", err, test.wantCode)
				}
				return
			}
			if err != nil {
				t.Fatal(err)
			}
			if got.Policy != test.wantPolicy || got.BaseURL != test.wantBase {
				t.Fatalf("link config = %+v, want policy=%q base=%q", got, test.wantPolicy, test.wantBase)
			}
		})
	}
}

func TestPDFCommandExportsWithInstalledChromium(t *testing.T) {
	path := "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
	if _, err := os.Stat(path); err != nil {
		t.Skip("installed Chromium unavailable")
	}
	output := filepath.Join(t.TempDir(), "page.pdf")
	var stderr bytes.Buffer
	command := NewRootCommand(Dependencies{
		Stdin: strings.NewReader("# PDF command E2E\n"), Stderr: &stderr,
		Build: testBuildInfo(), WorkingDirectory: t.TempDir(),
		NextExecutionID: func() margo.ExecutionID { return "cli-pdf-e2e" },
	})
	command.SetArgs([]string{"pdf", "-", "--output", output, "--engine", "chromium", "--engine-path", path})
	ctx, cancel := context.WithTimeout(context.Background(), 20*time.Second)
	defer cancel()
	if err := command.ExecuteContext(ctx); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(output)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.HasPrefix(data, []byte("%PDF-")) || len(data) < 1000 || stderr.Len() != 0 {
		t.Fatalf("PDF bytes = %d stderr = %q", len(data), stderr.String())
	}
}

func TestPDFCommandExportsMixedStaticAndInteractiveCharts(t *testing.T) {
	path := "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
	if _, err := os.Stat(path); err != nil {
		t.Skip("installed Chromium unavailable")
	}
	output := filepath.Join(t.TempDir(), "charts.pdf")
	markdown := `# Printable charts

` + "```goshtosochart" + `
schemaVersion: 1
type: bar
title: Static revenue
categories: [Q1, Q2]
series: [{name: Revenue, values: [12, 18]}]
` + "```" + `

` + "```goshtosochart" + `
schemaVersion: 1
type: line
renderer: interactive
title: Interactive revenue
categories: [Q1, Q2]
series: [{name: Revenue, values: [12, 18]}]
` + "```" + `
`
	var stderr bytes.Buffer
	command := NewRootCommand(Dependencies{
		Stdin: strings.NewReader(markdown), Stderr: &stderr,
		Build: testBuildInfo(), WorkingDirectory: t.TempDir(),
		NextExecutionID: func() margo.ExecutionID { return "cli-pdf-mixed-charts" },
	})
	command.SetArgs([]string{"pdf", "-", "--output", output, "--engine", "chromium", "--engine-path", path})
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	if err := command.ExecuteContext(ctx); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(output)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.HasPrefix(data, []byte("%PDF-")) || len(data) < 1000 || stderr.Len() != 0 {
		t.Fatalf("PDF bytes = %d stderr = %q", len(data), stderr.String())
	}
}

func TestPDFChartDataPrintGateDefaultsOffAndCanBeEnabled(t *testing.T) {
	markdown := `# Printable chart

` + "```goshtosochart" + `
schemaVersion: 1
type: bar
title: Revenue
categories: [Q1, Q2]
series: [{name: Revenue, values: [12, 18]}]
` + "```" + `
`
	for _, test := range []struct {
		name       string
		extraArgs  []string
		wantMarker string
	}{
		{name: "default off", wantMarker: `data-margo-chart-print-data="disabled"`},
		{name: "explicit on", extraArgs: []string{"--print-chart-data"}, wantMarker: `data-margo-chart-print-data="enabled"`},
	} {
		t.Run(test.name, func(t *testing.T) {
			engine := &capturingEngine{name: "native"}
			probe := engines.Probe{Native: func(context.Context) (pdf.Engine, engines.Candidate) {
				return engine, engines.Candidate{Name: "native", Version: "test", Compiled: true, Available: true}
			}}
			output := filepath.Join(t.TempDir(), "chart.pdf")
			command := NewRootCommand(Dependencies{
				Stdin: strings.NewReader(markdown), EngineProbe: probe, Stderr: io.Discard,
				Build: testBuildInfo(), WorkingDirectory: t.TempDir(),
				NextExecutionID: func() margo.ExecutionID { return "cli-pdf-chart-data" },
			})
			args := []string{"pdf", "-", "--output", output, "--engine", "native"}
			command.SetArgs(append(args, test.extraArgs...))
			if err := command.ExecuteContext(context.Background()); err != nil {
				t.Fatal(err)
			}
			if !bytes.Contains(engine.request.HTML, []byte(test.wantMarker)) {
				t.Fatalf("PDF HTML missing %q", test.wantMarker)
			}
		})
	}
}

func TestPDFCommandProducesCleanPopplerStructureForStaticPrintProjection(t *testing.T) {
	browserPath := installedCLITestChromium()
	pdfinfoPath, err := exec.LookPath("pdfinfo")
	if browserPath == "" || err != nil {
		t.Skip("installed Chromium and Poppler pdfinfo are required")
	}
	output := filepath.Join(t.TempDir(), "structure.pdf")
	markdown := "# Structure\n\n**Strong** and *emphasized*.\n\n- [x] Completed task\n\n| Column |\n| --- |\n| value |\n"
	command := NewRootCommand(Dependencies{
		Stdin: strings.NewReader(markdown), Stderr: io.Discard,
		Build: testBuildInfo(), WorkingDirectory: t.TempDir(),
		NextExecutionID: func() margo.ExecutionID { return "cli-pdf-structure" },
	})
	command.SetArgs([]string{"pdf", "-", "--output", output, "--engine", "chromium", "--engine-path", browserPath})
	ctx, cancel := context.WithTimeout(context.Background(), 20*time.Second)
	defer cancel()
	if err := command.ExecuteContext(ctx); err != nil {
		t.Fatal(err)
	}
	var stderr bytes.Buffer
	probe := exec.CommandContext(ctx, pdfinfoPath, "-struct", output)
	probe.Stdout = io.Discard
	probe.Stderr = &stderr
	if err := probe.Run(); err != nil {
		t.Fatalf("pdfinfo -struct: %v: %s", err, stderr.String())
	}
	if stderr.Len() != 0 {
		t.Fatalf("pdfinfo -struct warnings:\n%s", stderr.String())
	}
}

func TestPDFRenderFailureDoesNotFallbackToNative(t *testing.T) {
	directory := t.TempDir()
	path := testBrowserFile(t, directory, "chromium")
	chromium := &countingEngine{name: "chromium", exportErr: errors.New("pdf.render_failed: boom")}
	native := &countingEngine{name: "native"}
	probe := engines.Probe{
		LookupEnv: func(name string) (string, bool) {
			if name == "MARGO_CHROMIUM_PATH" {
				return path, true
			}
			return "", false
		},
		LookPath: func(string) (string, error) { return "", os.ErrNotExist }, Stat: os.Stat,
		ChromiumVersion: func(context.Context, string) (string, error) { return "Chromium test", nil },
		ChromiumEngine:  func(string) (pdf.Engine, error) { return chromium, nil },
		Native: func(context.Context) (pdf.Engine, engines.Candidate) {
			return native, engines.Candidate{Name: "native", Version: "native-test", Compiled: true, Available: true}
		},
		KnownPaths: []string{}, GOOS: "linux",
	}
	output := filepath.Join(directory, "missing.pdf")
	command := NewRootCommand(Dependencies{
		Stdin: strings.NewReader("# Failure\n"), EngineProbe: probe, Stderr: io.Discard,
		Build: testBuildInfo(), WorkingDirectory: directory,
		NextExecutionID: func() margo.ExecutionID { return "cli-no-fallback" },
	})
	command.SetArgs([]string{"pdf", "-", "--output", output})
	if err := command.ExecuteContext(context.Background()); cliDiagnosticCode(err) != "pdf.render_failed" {
		t.Fatalf("error = %v", err)
	}
	if chromium.exports != 1 || native.exports != 0 {
		t.Fatalf("chromium exports = %d native exports = %d", chromium.exports, native.exports)
	}
	if _, err := os.Stat(output); !os.IsNotExist(err) {
		t.Fatalf("output stat error = %v", err)
	}
}

type countingEngine struct {
	name      string
	exportErr error
	exports   int
}

type capturingEngine struct {
	name    string
	request pdf.Request
}

func installedCLITestChromium() string {
	for _, candidate := range []string{
		"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
		"/opt/homebrew/bin/chromium",
	} {
		if info, err := os.Stat(candidate); err == nil && info.Mode().IsRegular() {
			return candidate
		}
	}
	for _, name := range []string{"google-chrome", "chromium", "chromium-browser"} {
		if path, err := exec.LookPath(name); err == nil {
			return path
		}
	}
	return ""
}

func (engine *countingEngine) Name() string { return engine.name }
func (engine *countingEngine) Version(context.Context) (string, error) {
	return engine.name + "-test", nil
}
func (engine *countingEngine) Export(context.Context, pdf.Request) (pdf.Result, error) {
	engine.exports++
	return pdf.Result{}, engine.exportErr
}

func (engine *capturingEngine) Name() string { return engine.name }
func (engine *capturingEngine) Version(context.Context) (string, error) {
	return "test", nil
}
func (engine *capturingEngine) Export(_ context.Context, request pdf.Request) (pdf.Result, error) {
	engine.request = request.Clone()
	tasks := make([]margo.RuntimeTaskReport, len(request.Runtime.Tasks))
	for index, task := range request.Runtime.Tasks {
		tasks[index] = margo.RuntimeTaskReport{
			ID: task.ID, Kind: task.Kind, InputSHA256: task.InputSHA256,
			OutputSHA256: strings.Repeat("a", 64), OutputBytes: 1, Status: margo.RuntimeTaskSucceeded,
		}
	}
	return pdf.Result{
		PDF: []byte("%PDF-test"),
		Runtime: margo.RuntimeReport{
			Protocol: request.Runtime.Protocol, DocumentFingerprint: request.Runtime.DocumentFingerprint,
			RenderInstanceID: request.Runtime.RenderInstanceID, ExecutionID: request.ExecutionID,
			Status: margo.RuntimeReady, Tasks: tasks, FontChecks: []margo.FontCheck{},
			BlockedRequests: []margo.BlockedRequest{}, Layout: margo.LayoutMetrics{ScrollWidth: 1, ScrollHeight: 1},
		},
		Engine: pdf.EngineInfo{Name: engine.name, Version: "test"},
	}, nil
}
